language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t fgiraldolumu/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true fgiraldolumu/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-699678850662"
  bucket_path: "docker"
  on:
    branch: master
    access_key_id: $AWs_ACCESS_KEY
    secret_access_key:
      secure: "$AWs_SECRET_KEY"